### ISSUE TITLE
右下角缩小按钮功能异常

### ISSUE THREAD

**Issue by ON0thing** [ikuaitu/vue-fabric-editor#204]
问题：右下角缩小按钮连续按到最小后，再继续按会变放大，再继续按会放大画布内物件，同时标尺失效。

请教：能否添加画布内图片宽高的提示？（比如说当鼠标移动到该图片后弹出提示框）

**Comment by a847244052** [comment]
已pr

**Comment by nihaojob** [comment]
@ON0thing 感谢你的反馈，问题已经被 @a847244052 大佬解决，已经合并到主分支，可以更新代码再试下。

关于 “能否添加画布内图片宽高的提示？”的问题，我们目前在升级TS语法和设计插件化方案，增加提示的需求并不是紧急且必要的事情，如果你愿意在项目上提交PR来支持该功能我们是支持的，可以让代码尽量保持在1个模块中。

我的实现思路是：
1. 在Core中单独增加一个模块文件，参考 辅助线获模块获其他模块。
2. 增加move监听事件，如果move时，经过的元素是图片，则获取图片宽高并展示。

可能遇到的问题：由于其他功能都依赖move事件，很可能会引发事件的冲突，比如绘制线条时经过图片，或者拖拽画布时经过图片。

**Comment by nihaojob** [comment]
> 当画布的max size设置较大时，比如20000，并且画布设置较大(18000X6000)，载入时或者按右下角工具条最后一个自适应按钮时， 显示的画布是一个正方形与设置不符。

没太明白，是否可以录制gif或者视频看下。
