### ISSUE TITLE
希望能使用element-plus作为UI框架

### ISSUE THREAD

**Issue by ijry** [ikuaitu/vue-fabric-editor#344]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Qiu-Jun** [comment]
暂不考虑更改ui库，ui库都差不多，你可以考虑自己弄一个，核心代码都在packages/core了

**Comment by nihaojob** [comment]
https://github.com/ikuaitu/element-fabric-editor   请关注该仓库，即将推出element-plus版本

**Comment by ijry** [comment]
> https://github.com/ikuaitu/element-fabric-editor 请关注该仓库，即将推出element-plus版本

🐂，怎么做，是直接拷贝这个，改UI吗？
