### ISSUE TITLE
模板流布局更新

### ISSUE THREAD

**Issue by nihaojob** [ikuaitu/vue-fabric-editor#431]
首页左侧列表中，支持流式布局

![image](https://github.com/nihaojob/vue-fabric-editor/assets/13534626/9b5aa16a-6941-4999-8b01-bb8159bf2ae7)

**Comment by AliceLanniste** [comment]
这个流布局是不是和下面这个差不多
<img width="659" alt="image" src="https://github.com/nihaojob/vue-fabric-editor/assets/17617116/948a1dba-081f-44a0-bb68-c32da2050f02">

**Comment by nihaojob** [comment]
嗯嗯 对  不过这个是基于JS实现的 可能会影响翻页

**Comment by AliceLanniste** [comment]
> 嗯嗯 对 不过这个是基于JS实现的 可能会影响翻页

我没明白你的意思，左侧模板这个没有翻页是下滑加载模板

**Comment by nihaojob** [comment]
> > 嗯嗯 对 不过这个是基于JS实现的 可能会影响翻页
> 
> 我没明白你的意思，左侧模板这个没有翻页是下滑加载模板

https://nihaojob.github.io/vue-fabric-editor/#/template  这个页面没有滚动翻页，使用JS来实现流布局是没问题的，

编辑器页面左侧的模板，是用的滚动翻页，如果同样使用js实现流布局 可能会有影响翻页哈  具体得测试一下了

**Comment by AliceLanniste** [comment]
> > > 嗯嗯 对 不过这个是基于JS实现的 可能会影响翻页
> > 
> > 
> > 我没明白你的意思，左侧模板这个没有翻页是下滑加载模板
> 
> https://nihaojob.github.io/vue-fabric-editor/#/template 这个页面没有滚动翻页，使用JS来实现流布局是没问题的，
> 
> 编辑器页面左侧的模板，是用的滚动翻页，如果同样使用js实现流布局 可能会有影响翻页哈 具体得测试一下了

也就是说模板流布局的依赖包是通过js来实现，但是左侧模板会有影响是吧

**Comment by AliceLanniste** [comment]
> > > 嗯嗯 对 不过这个是基于JS实现的 可能会影响翻页
> > 
> > 
> > 我没明白你的意思，左侧模板这个没有翻页是下滑加载模板
> 
> https://nihaojob.github.io/vue-fabric-editor/#/template 这个页面没有滚动翻页，使用JS来实现流布局是没问题的，
> 
> 编辑器页面左侧的模板，是用的滚动翻页，如果同样使用js实现流布局 可能会有影响翻页哈 具体得测试一下了

我试了下，单纯用css的话是没法达到期望效果的
