### ISSUE TITLE
文字尺寸修改异常

### ISSUE THREAD

**Issue by MarkGor** [ikuaitu/vue-fabric-editor#443]
1、插入文字，双击进入编辑，然后通过快捷键 CTRL + X 剪切编辑框中文字；
2、在编辑框中直接粘贴上，此时修改字体大小颜色等均失效。

**Comment by MarkGor** [comment]
发现问题了；
如果activeObject存在style属性，怎么改都不会生效；
暂时在attributeFont 和 attributeColor里临时fix，请问这样会有什么影响吗？
`const changeCommon = (key, value) => {
  const activeObject = canvasEditor.canvas.getActiveObjects()[0];
  if (activeObject) {
    activeObject && activeObject.set(key, value);
//在这里增加了同步修改style里面的属性
    if (Object.values(activeObject.styles).length > 0) {
      Object.values(activeObject.styles).forEach((item) => {
        for (let x in item) {
          if (typeof item[x][key] !== 'undefined') {
            item[x][key] = value;
          }
        }
      });
    }
//在这里增加了同步修改style里面的属性
    canvasEditor.canvas.renderAll();
  }
};`

**Comment by nihaojob** [comment]
可以找下 fabric的相关文档，有针对鼠标选中文字的样式修改方法
