### ISSUE TITLE
你好，请问画布放大后拖拽空白区域对目标元素进行编辑，再点击目标元素点不中，我设置的是实际的xy值，这个问题请问怎么处理

### ISSUE THREAD

**Issue by zhangbo87** [ikuaitu/vue-fabric-editor#472]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wuchenguang1998** [comment]
你好，可以给出详细的复现步骤吗

**Comment by zhangbo87** [comment]
![bug](https://github.com/user-attachments/assets/01893e77-3feb-41eb-adbf-d2e807966568)
你好我就是监听，me没有选中元素也就是空白区域，就可以移动画布，拖动后设置移动的位置，这样有个问题就是放大后选中目标元素会选的不准确，这个是要根据缩放倍数重新计算缩放后后的位置吗，那个中心点也移动到了画布中心，这个也会影响到放大后选中目标吧？
