### ISSUE TITLE
成组操作后，图层层级顺序发生非预期改变。详见下图说明

### ISSUE THREAD

**Issue by 24623253** [ikuaitu/vue-fabric-editor#480]
成组前，矩形在圆型上方，成组后矩形却在圆形下方；可以多添加几个元素，在成组后，图层顺序会更加不可预期
![2D566D33-B66B-4d79-B4EC-F79E16CB87BC](https://github.com/user-attachments/assets/14e6af47-c4fd-4380-abae-4c062545aa29)
![19828527-3F1D-4ea2-A0C2-D7CF03FD7C70](https://github.com/user-attachments/assets/6df7f8e5-2998-419c-93d8-8909d539f427)

**Comment by nihaojob** [comment]
感谢您的反馈 我们按照步骤尝试进行复现 并没有复现您说的情况，是否能提供可复现的步骤或者 demo?
![image](https://github.com/user-attachments/assets/63c8813b-2265-4dbe-b405-e91e76b30520)

**Comment by nihaojob** [comment]
由于此 issue 两天内内一直未收到回复，无法进行有效的处理和推进，所以不得不将其关闭。若后续有回复并需要重新开启，可联系相关负责人。
