### ISSUE TITLE
路径文本元素与其他元素打组，画布异常

### ISSUE THREAD

**Issue by wuchenguang1998** [ikuaitu/vue-fabric-editor#488]
绘制一个路径文本元素，并和其他元素打成组，画布异常
![image](https://github.com/user-attachments/assets/95365b1b-d556-485a-9df5-51f3ca657b73)
打开控制台，发现是fabricjs内部报错
![image](https://github.com/user-attachments/assets/c5700b14-ca87-40b2-b238-0b8046fbf882)
查阅fabricjs[对应文档](http://fabricjs.com/docs/fabric.IText.html#path)，发现路径文本功能还处在beta版本

**Comment by AliceLanniste** [comment]
那这个bug只能等fabric修复了

**Comment by nihaojob** [comment]
目前看路径文本元素 并不是一个特别刚需的功能 很少有开发者提到希望一定要加这个功能  如果影响比较大 可以先隐藏掉相关功能
