### ISSUE TITLE
Undo功能的Bug

### ISSUE THREAD

**Issue by Iwiii** [ikuaitu/vue-fabric-editor#509]
**Describe the bug**
删除图片元素的后再使用撤销功能 有时会无法恢复被删除图片

**To Reproduce**
1. 打开 https://www.kuaitu.cc/#/?tempId=54 
2. 选中任意一个图片元素 按delete键进行删除操作 此时图片消失 
3. 点击撤销按钮 直到图片恢复货按钮不可点
4.  第3条一般会出现两种情况,1.点击多次图片恢复(预期是点击1次) 2.点击多次图片不恢复且撤销按钮变灰
5. 如果出现第3条的第1种情况,重复2,3操作,多次操作后会出现第4条的第二种情况
6. See error

**Expected behavior**
正常应该是删除图片后点击撤销 会立马恢复被删除图片

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version 版本 124.0.6367.62（正式版本） (arm64)

**Additional context**

**Comment by nihaojob** [comment]
https://github.com/ikuaitu/vue-fabric-editor/pull/521  感谢反馈  其他大佬已经 PR 修复。
