### ISSUE TITLE
undo redo bug

### ISSUE THREAD

**Issue by zhangbo87** [ikuaitu/vue-fabric-editor#522]
**Describe the bug**
你好这个撤销和重做测试下来还是有bug比如移动画布上的一个元素就会存在撤销不了的情况
[
![bug](https://github.com/user-attachments/assets/b884710d-42db-4393-8b38-654172c13e08)
](url)
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zhangbo87** [comment]
我删掉，再撤销，再删除，然后再撤销就出不来了

**Comment by nihaojob** [comment]
可以参考下 大佬的 PR  https://github.com/ikuaitu/vue-fabric-editor/pull/521  对错误进行了修正，后边会合并到分支。

**Comment by nihaojob** [comment]
https://github.com/ikuaitu/vue-fabric-editor/pull/521   已合并到主分支
