### ISSUE TITLE
【送鼠标需求】拆分 index.vue 组件 和 css

### ISSUE THREAD

**Issue by nihaojob** [ikuaitu/vue-fabric-editor#527]
## 背景

现在`src/views/home/index.vue`文件为编辑器入口，单个文件过大，需要将文件拆分出header、lefte、right组件，对组件进行归类，抽离相关逻辑和css,作为子组件引入到index.vue中。

## 目标
让 index.vue 变小，让组件目录更清晰，功能不变。

## 参考形式
index.vue
![image](https://github.com/user-attachments/assets/99cf647d-f5e0-4943-95d0-d87875850912)

top.vue
![image](https://github.com/user-attachments/assets/cd648d2d-fa7e-4eee-b246-ac288fd160b2)

left.vue
![image](https://github.com/user-attachments/assets/f7f3e8c3-8759-463e-8e38-4d5ec11686d9)

right.vue
![image](https://github.com/user-attachments/assets/1fb0ac8d-1fb7-4351-9d76-bf8f09310b37)

**Comment by Asher-Tan** [comment]
#531

**Comment by jdpoccorie** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by nihaojob** [comment]
https://github.com/ikuaitu/vue-fabric-editor/pull/531
