### ISSUE TITLE
【送鼠标需求】将行内 svg代码替换为 svg 图标

### ISSUE THREAD

**Issue by nihaojob** [ikuaitu/vue-fabric-editor#528]
## 背景
现在代码中包含太多行内svg代码，将所有svg代码替换为svg文件图标。
![image](https://github.com/user-attachments/assets/c08980dc-084b-4014-a0ac-a9c0761864ab)
![image](https://github.com/user-attachments/assets/81e8ea8e-8510-4223-b751-f196095a7710)

## 目标
提高代码可读性，让svg维护更方便，注意 SVG 图片大小和颜色，需保持一致。

## 参考形式
![image](https://github.com/user-attachments/assets/e5d07854-dab7-44ef-b033-0f2ff202f8ae)

**Comment by jdpoccorie** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
