### ISSUE TITLE
【送鼠标需求】弹框图片截图

### ISSUE THREAD

**Issue by nihaojob** [ikuaitu/vue-fabric-editor#541]
封装为通用组件，选中单个图片，右侧出现裁剪按钮，点击裁剪可以弹出弹框进行调整。
拖拽组件不可超出图片区域。
![image](https://github.com/user-attachments/assets/13731a0b-027d-486d-bafb-34899c3f42bc)

**Comment by x007xyz** [comment]
现在的这个功能在哪里？主分支里好像没有这个功能

**Comment by nihaojob** [comment]
> 现在的这个功能在哪里？主分支里好像没有这个功能

现在还没有这个功能哈，需要在选中图片时，右侧属性面板增加一个裁剪按钮，点击后弹出弹框，点击弹框内完成按钮后，替换掉画布中的图片。

**Comment by x007xyz** [comment]
> > 现在的这个功能在哪里？主分支里好像没有这个功能
> 
> 现在还没有这个功能哈，需要在选中图片时，右侧属性面板增加一个裁剪按钮，点击后弹出弹框，点击弹框内完成按钮后，替换掉画布中的图片。

OK
